# Intentional top-level command-line tools. Homebrew manages their dependencies.
brew "awscli"
brew "bat"
brew "chezmoi"
brew "coreutils"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "gitleaks"
brew "gnupg"
brew "jq"
brew "lazygit"
brew "lsof"
brew "neovim"
brew "pinentry-mac"
brew "qemu"
brew "ripgrep"
brew "sevenzip"
brew "starship"
brew "tree"
brew "wget"
brew "zoxide"

# Zsh completions and interactive UI plugins.
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# Intentional macOS applications and command-line casks.
cask "1password-cli"
cask "alt-tab"
cask "codex"
cask "font-meslo-lg-nerd-font"
cask "ghostty"
cask "multipass"
cask "rectangle"
cask "tailscale-app"
cask "vlc"
cask "zulu@17"

# Python tool used by the managed browser-testing workflow.
uv "browser-harness"
