
# pre-requisites for theme:
# git clone https://github.com/alacritty/alacritty-theme themes
# curl https://raw.githubusercontent.com/josean-dev/dev-environment-files/main/.config/alacritty/themes/themes/coolnight.toml --output ~/.config/alacritty/themes/themes/coolnight.toml
#
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
startup_mode = "Maximized"

opacity = 0.7
blur = false

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14


